# 
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: company.com
    Template:
      Count: 3

# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Provider
  # ---------------------------------------------------------------------------
  - Name: Provider
    Domain: provider.company.com
    EnableNodeOUs: true
  
    Template:
      Count: 2
  
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Consumer
  # ---------------------------------------------------------------------------
  - Name: Consumer
    Domain: consumer.company.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
 